Checkbox component
dsausa/dsa-ui pull request #44
Opened 2022-11-06 23:35 UTC by ysulyma

This implements `dsa-checkbox` component, which resolves #33. Draft PR since I have some questions:

- in React, I often do
```tsx
export function Checkbox(props: React.InputHTMLAttributes<HTMLInputElement>) {
  const {children, ...attrs} = props;
  return (
    <>
      <input type="checkbox" {...attrs} />
      <label htmlFor={id}>{children}</label>
    </>
  );
}

2022-11-07 02:54 UTC, nedredmond commented
That's not a feature of Stenciljs or its major competitor Lit Element. Custom elements offer more explicit control over the underlying elements. We will have to be opinionated, I suppose! We can always make adjustments to the UX in the future.

2022-11-07 12:47 UTC, erikdstock reviewed
A couple drive-by questions, nothing big yet.

2022-11-07 12:47 UTC, erikdstock commented on wc/src/components.d.ts
> +    };
Is this definition file generated?

2022-11-07 12:47 UTC, erikdstock commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.css
> +}
basic question: What does this selector do? I saw it yesterday when poking around but didn't want to get sidetracked. I supposed it has to do with the Stencil `Host` element referenced in the next file.

2022-11-07 12:47 UTC, erikdstock commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +      </Host>
This gets into the sort of implementation questions I think we'll be uncovering as we work. I think it's generally reasonable to add labels to checkboxes but is it always necessary, should there always be one space between the box and the label, and so on?

This led me to read [about `<slot />`](https://stenciljs.com/docs/templating-jsx#slots) and I have more questions - it seems we can't access a `children` unless we use a functional component, which behaves differently in stenciljs, so slot is the only way. I was thinking we just make the label optional based on presence of a passed `children`, but from my few minutes of searching it seems impossible for the WC to know what children it has - only `<slot />`.

Minor issue for this PR, but a bigger question for how stencil works

2022-11-07 12:51 UTC, erikdstock commented
> That's not a feature of Stenciljs or its major competitor Lit Element. Custom elements offer more explicit control over the underlying elements. We will have to be opinionated, I suppose! We can always make adjustments to the UX in the future.

I was surprised at this too, as the `const { propForA, ...propsForB} = props` construct seems like it would be so useful for web components. I think i am just gonna need more time understanding what WCs are besides pre-styled components and counters/timers.

Side question: How much can components know about their enclosing context? Can they adjust for dark mode?

2022-11-07 16:50 UTC, nedredmond commented on wc/src/components.d.ts
> +    };
Yes!

2022-11-07 16:53 UTC, nedredmond commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.css
> +}
Host refers to the container of the web component. See https://stenciljs.com/docs/host-element

2022-11-07 17:17 UTC, nedredmond requested changes
@ysulyma , excellent start! I'd like to see an API created for this element for external control-- maybe a developer would like the component to start in the `checked` state, for instance. Let's get some `@Prop()`s in there.

Also, and this is a stretch goal (we can implement this later), I'd like to see some `aria` a11y attributes present. Here is some documentation: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/

2022-11-07 17:17 UTC, nedredmond commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +          <slot />
issue: Per the conversation below, I think we'd want `label` to render conditionally here. Also, we would want some way to determine if that label should render to the left, right, above, or below.

I'd like to see a `Prop() label: string;` to accept label text. Its presence can determine whether the label should render. We can punt the issue of where the label renders in relation to the input, but that could be something to think about-- maybe conditionally add styles to the `Host` to render as a row or a column, and another prop to determine the cardinal position relative to the input.

2022-11-07 17:17 UTC, nedredmond commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +  private id = 'id';
issue: How about we accept an 'id' as a prop? This will create `id` collision if there is more than one checkbox in the view.

2022-11-09 14:38 UTC, erikdstock commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +      </Host>
great, followup question - say i want the label to appear elsewhere. Can I make it outside the WC and still create the `htmlFor` reference?

2022-11-10 01:56 UTC, ysulyma commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +      </Host>
Yes, there will always be a `<label>` with a checkbox. More to the point, even if there were a situation where we wanted a checkbox with no label, this is a checkbox-with-a-label component.

Some of this gets to styles-vs-components; styling native components is much easier than doing a bunch of ARIA stuff and input handling to recreate them.

I used `<slot>` in case we wanted to have an icon as part of the label text.

Stencil seems to use the same JSX syntax as React, even though it's not using React. `for={}` gives a warning.

2022-11-10 01:57 UTC, ysulyma commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +  private id = 'id';
`id`s are scoped to the shadow root

2022-11-13 04:36 UTC, nedredmond commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +  private id = 'id';
Oh, dope!

2022-11-13 04:38 UTC, nedredmond commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +      </Host>
@erikdstock In that case, you could provide an `id` or `name` as a prop and use that in the external label. It should work as expected.

2022-11-13 04:43 UTC, nedredmond commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +      </Host>
@ysulyma Just a thought since using `<slots>` dynamically is not trivial, and we probably want some flexibility:

What if we have separate `dsa-checkbox` and `dsa-checkbox-icon` components? That way, we could still render each dynamically based on provided properties.

`dsa-checkbox-icon` could use what @erikdstock implements, and be mostly the same except adding an icon at the start of a label (or whatever the designers decide, based on the label position).

However, I do see some use cases for `slot`, when we may want an anchor link or tooltip on the label/icon. It's an interesting problem.

2022-11-13 05:00 UTC, ysulyma commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +      </Host>
@nedredmond @erikdstock if you want the label to appear somewhere completely different on screen, away from the checkbox, then you should be using `<label>` and `<input>` directly instead of this component.

It is possible for a `<label>` to reference an `<input>` inside a Custom Element if and only if the Custom Element is not using ShadowDOM. If we wanted to enable that for this component (which I don't think we do), we'd need to remove `shadow: true` from `dsa-checkbox.tsx`.

2022-11-13 05:09 UTC, ysulyma commented
re: dark mode, there is [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), but as Ned observed it doesn't work in Chrome (or at least Chromium). You need to make Light/Dark mode toggle-able on the page itself, and use `prefers-color-scheme` to guess the initial value.

2022-11-13 05:50 UTC, ysulyma commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +          <slot />
@nedredmond how would we use `aria-*` attributes here? They're meant for when you use like a `<div>` + Javascript to emulate a checkbox, not on native `<input type="checkbox">`. Do you mean via `attachInternals()`? From what I can tell that's not supported yet in Stencil: https://github.com/ionic-team/stencil/issues/2284

2022-11-19 20:25 UTC, ysulyma commented
General issue: from what I can tell, it is not possible to use `shadow: true` on form elements until StencilJS supports [formAssociated](https://github.com/ionic-team/stencil/issues/2284) (or else there's no way to get `name` and `value`). We can however use `scoped: true`, which prevents styles from leaking upwards, although it could allow styles to leak inwards.

2022-11-19 20:25 UTC, ysulyma commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +  private id = 'id';
This no longer applies since `shadow: true` seems to be unusable for form components (see other comment). A solution is to wrap the `<input>` in the `<label>` so no ID is needed.

2022-11-19 22:18 UTC, nedredmond commented
@ysulyma While this is a bummer, it does look like there is recent work to get this feature added. Besides, this isn't a blocker-- we can use events to communicate with the parent component. While it'd be great if these components could participate natively in html forms, that can be a future refactor, and in the meantime we can work with events. It's clunkier for sure but it will work for now.

2022-11-19 23:48 UTC, nedredmond commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.tsx
> +  private id = 'id';
`formAssociated` is a new feature, and it's nice, but devs have been creating forms from web components long before that was introduced. [Besides, it's not yet supported by Safari.](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals#browser_compatibility)

We just need to handle form components through events for now, and we can refactor once this feature is universally supported (as well as by Stenciljs).

2022-11-21 01:39 UTC, ysulyma commented
Heavily rewritten, let me know what you think! Depends on #93. One thing I wasn't sure about is whether `checked` should behave as in HTML or React: `<input checked>` in HTML is more like `<input defaultChecked>` in React, whereas `<input checked>` in React is more like `input.checked = true` in DOM.

2022-11-21 23:12 UTC, nedredmond approved these changes
This is cool! Thanks for all of your hard work on this. The logic you added to handle events is interesting and I'm excited to learn more about it!

I don't think I'm sold on using slot here but we'll see how it goes. I'm sure it will our needs for now.

WOOHOO first real web component!

2022-11-21 23:12 UTC, nedredmond commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.css
> +:host input {
Not a problem, but why drill down from host instead of applying a class?

2022-11-22 03:22 UTC, ysulyma commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.css
> +:host input {
personal tic; in fact I don't think I even need `:host` here, do I? Since the CSS is scoped to the shadow tree anyway

2022-11-22 03:30 UTC, ysulyma commented on wc/src/components/forms/dsa-checkbox/dsa-checkbox.css
> +:host input {
ah, I suppose an evil person could put another `<input/>` inside the `<slot/>`, which this selector would inadvertently hit. (The main motivation for the `<slot/>` is like a Terms and Conditions link)

2022-11-22 05:02 UTC, ysulyma commented
I didn't know about the `formdata` event before, that's the main reason I thought I needed `formAssociated`.

I set up this PR so #93 would merge first and then this one would merge into main. Or should I merge this one into `yuri/checkbox-prelims` now?

2022-11-23 16:18 UTC, nedredmond commented
> I didn't know about the `formdata` event before, that's the main reason I thought I needed `formAssociated`.
> 
> I set up this PR so #93 would merge first and then this one would merge into main. Or should I merge this one into `yuri/checkbox-prelims` now?

You can let this sit until the other one's approved. Up to you!

2022-11-26 02:47 UTC, merged